### PR TITLE
chore: bump zksolc to 1.5.4

### PR DESCRIPTION
**Pull request by elfedy**
## Motivation

https://github.com/matter-labs/era-compiler-solidity/releases/tag/1.5.4

### CODE REVIEW

**Comment by Karrq** [comment]
does compilers support it? also, why are we not using `ZKSOLC_VERSION` from compilers?

**Comment by elfedy** [comment]
> does compilers support it? also, why are we not using `ZKSOLC_VERSION` from compilers (here and in other parts)?

@Karrq as far as I read/tested there are no breaking changes for this version so it does in this case.

As for using the compilers constant we may or may not want to do this, that constant was set for test defaults mostly. What we set is just a default, we need to revise having a "supported" version and warning if it is not used, at that point we can migrate to using that value

**Comment by nbaztec** [comment]
I guess this PR is obsolete? No changes.

**Comment by elfedy** [comment]
Seems it was bumped on https://github.com/matter-labs/foundry-zksync-book/pull/29

**Pull request closed without merging**
